spring:
  application:
    name: eureka


server:
  port: 8761

#we need this configuration so we don't register the eureka server with itself
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
